# install the association rules package before you get started...
install.packages("arules")

#load the packages for association rules and R sample datasets
library(arules)
library(datasets)

#load the grocery basket dataset - uncomment the line below to just load the
#groceries dataset from the built in datasets package...
data(Groceries)
summary(Groceries)
#Alternatively, you could load your own dataset directly - e.g., from a .csv file.
#Note that the association rules algorithm expects you to load your data in "transaction" format
#this means you need to load it using the read.transactions() function, rather than the read.csv function
#you can use the groceries.csv file from Moodle if you would like to try this. 

#setwd(choose.dir()) 
#Groceries <- read.transactions("groceries.csv",format=c("basket"),sep=",", rm.duplicates=TRUE)

#plot the 'count' of each grocery item appearing in the dataset,
#from most common on down, but only show the first 20
itemFrequencyPlot(Groceries,topN=20,type="absolute")

#the command to generate association rules in R is called apriori,
#which refers to the aprior algorithm. We will assign the algorithm's
#output to 'rules', which is a data frame.
#some notes: you always have to specify the min support and min confidence
#rules that do not have at least this support and confidence will be ignored
rules <- apriori(Groceries,parameter=list(supp = 0.001, conf=0.8))

#because the support and confidence results may go to many decimal places,
#we will first specify that we only want to see two decimal places for any
#numeric output
options(digits=2)

#we'll now ask R to summarize the set of rules it generated from our data
#this tells us the number of rules generated by length (number of items),
#amongst other things
summary(rules)

#next we will ask R to report back the top 5 rules that were just identified, 
#along with their measures of support, confidence and lift.
inspect(rules[1:5])

#depending on the measure we care about, we can sort the rules before looking
#at the top candidates. This command sorts the rules based on lift.
#we then reinspect the top 5.
rules <- sort(rules,by="lift",decreasing=TRUE)
inspect(rules[1:5])

#now lets generate rules where we fix some values in the LHS 
#say we only want to include rules where whole milk is on the LHS...
#Note, %pin% allows you to do partial matching
inspect(subset(rules, subset = lhs %pin% "whole milk" & lift >5.2))


#############################
# Handling with Matrix Data #
#############################
data = read.csv("CatalogCrossSell.csv")
matrix_format = data.matrix(data[,2:10]) # get ride of customer id, otherwise will be taken as an "item"
transaction = as(matrix_format, "itemMatrix")
rules <- apriori(data = transaction, parameter = list(support = 0.25, confidence = 0.8))
rules <- sort(rules,by="lift",decreasing=TRUE)
inspect(rules[1:5])